name: Publish Blazor App to GitHub Pages
on:
  push:
    branches:
      - main
      - release/*

# Required permissions for deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one deployment at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build & Publish Blazor App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the app
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish Blazor app
      run: dotnet publish src/BlazorApp -c Release -o published

    - name: Fix base href in index.html for GitHub Pages
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        echo "Repository Name: $
